name: laravel-kuis-deploy2

on:
  push:
    branches:
      - '*'
jobs:
  build:
    name: Deploy Deployment Configuration 
    runs-on: ubuntu-latest
    steps:
      - name: 'Deploy Deployment Configuration'
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{secrets.USERNAME}}
          key: ${{secrets.KEY}}
	  script: |
           sudo ls
