name: dev-laravel-kuis2

on:
  push:
    branches:
      - '*'
jobs:
  build:
  name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
	-name: test ssh
  	uses: appleboy/ssh-action@master
  	with:
    	host: ${{ secrets.HOST }}
    	username: ${{ secrets.USERNAME }}
    	key: ${{ secrets.KEY }}
    	port: ${{ secrets.PORT }}
    	script: |
      	whoami
      	ls -al
