name: laravel-kuis-deploy2

on:
  push:
    branches:
      - '*'
jobs:
  build:
    name: Deploy Deployment Configuration 
    runs-on: ubuntu-latest
    steps:
      - name: 'Pick docker comose as target'
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{secrets.USERNAME}}
          key: ${{secrets.KEY}}
          source: "docker-compose.yml"
          target: "./"

      - name: 'Deploy Deployment Configuration'
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{secrets.USERNAME}}
          key: ${{secrets.KEY}}
	  script: |
            sudo docker-compose up -d 
	    sudo chmod -R 777 /home/ubuntu/docker-laravel-kuis2/storage
	    sudo chmod -R 777 /home/ubuntu/docker-laravel-kuis2/bootstrap
	    sudo chmod -R 777 /home/ubuntu/docker-laravel-kuis2/public
	    sudo rm .env
	    sudo touch .env 
            sudo echo 'APP_NAME=${{secrets.APP_NAME}}' >> .env 
	    sudo echo 'APP_URL=${{secrets.HOST}}' >> .env
	    sudo echo 'APP_ENV=local' >> .env
	    sudo echo 'APP_KEY=${{secrets.APP_KEY}}' >> .env
	    sudo echo 'APP_DEBUG=true' >> .env
	    sudo echo 'LOG_CHANNEL=stack' >> .env
	    sudo echo 'LOG_LEVEL=debug' >> .env
	    sudo echo 'DB_CONNECTION=${{secrets.DB_CONNECTION}}' >> .env
	    sudo echo 'DB_HOST=${{secrets.DB_HOST}}' >> .env
	    sudo echo 'DB_PORT=${{secrets.DB_PORT}}' >> .env
	    sudo echo 'DB_DATABASE=${{secrets.DB_DATABASE}}' >> .env
	    sudo echo 'DB_USERNAME=${{secrets.DB_USERNAME}}' >> .env
	    sudo echo 'DB_PASSWORD=${{secrets.DB_PASSWORD}}' >> .env
	    sudo echo 'BROADCAST_DRIVER=log' >> .env
	    sudo echo 'CACHE_DRIVER=file' >> .env
	    sudo echo 'QUEUE_CONNECTION=sync' >> .env
	    sudo echo 'SESSION_DRIVER=file' >> .env
	    sudo echo 'SESSION_LIFETIME=120' >> .env
	    sudo cp .env /docker-laravel-kuis2
	    sudo docker exec -it showroom composer install
            sudo docker exec -it showroom php artisan migrate
	    sudo docker exec -it showroom php artisan db:seed
	    sudo docker exec -it showroom php artisan optimize:clear

