name: laravel-kuis-deploy2

on:
  push:
    branches:
      - '*'
jobs:
  build:
  name: Build and Deploy
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 'Running Test Sh'
  	uses: appleboy/ssh-action@master
        with:
    	host: ${{ secrets.HOST }}
    	username: ${{ secrets.USERNAME }}
    	key: ${{ secrets.KEY }}
    	port: ${{ secrets.PORT }}
    	script: |
            sudo whoami
